//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class IllnessHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IllnessHistory()
        {
            this.IllnessHistoryHasMedicines = new HashSet<IllnessHistoryHasMedicines>();
            this.PacientHasIllnesHistory = new HashSet<PacientHasIllnesHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan BeginDate { get; set; }
        public System.TimeSpan EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IllnessHistoryHasMedicines> IllnessHistoryHasMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacientHasIllnesHistory> PacientHasIllnesHistory { get; set; }
    }
}
