//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediCppEntities3 : DbContext
    {
        public MediCppEntities3()
            : base("name=MediCppEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<IllnessHistory> IllnessHistory { get; set; }
        public virtual DbSet<IllnessHistoryHasMedicines> IllnessHistoryHasMedicines { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Pacient> Pacient { get; set; }
        public virtual DbSet<PacientHasIllnesHistory> PacientHasIllnesHistory { get; set; }
    }
}
